version: '2'

services:
    broker:
        build: .
        image: broker
        container_name: broker
        links:
            - pubsub
        ports:
            - "8001:8001"
        entrypoint: /usr/bin/entrypoint.sh
        volumes:
              - /media/arquivos/idea-projects/omf_sfa:/root/omf_sfa
    pubsub:
        image: sameersbn/openfire:latest
        container_name: pubsub
        ports:
            - "9090:9090"
            - "5222:5222"
            - "7777:7777"
        volumes:
            - ./openfire:/var/lib/openfire
